### ISSUE TITLE
Version: 2.13.3

### ISSUE THREAD

**Issue by shahabmohi** [weDevsOfficial/happy-elementor-addons#56]
Version: 2.13.3 is incompatible with the latest version of Elementor and causes loading issues.

**Comment by pamdam** [comment]
same here , it doesnt seem to remember or just make it all come up double.

**Comment by obiPlabon** [comment]
Hello, @everyone we are really sorry for the inconvenience and trouble you went through. And the good news is we have released `v2.14.2` with all the JS and editor related fixes. Please update your HappyAddons asap to the latest version.

Details: https://wordpress.org/plugins/happy-elementor-addons/#developers

Thank you

**Comment by shahabmohi** [comment]
This is still not solved. Version: 2.14.2 is still incompatible with the latest version of Elementor and causes loading issues.
